### PR TITLE
How have your updates been working for you?

### PR DESCRIPTION
**Pull request by mmikeww**
I would've used the Issues or Discussions features but you dont seem to have those enabled, so I created a fake Pull Request

I found your fork looking through the original repo, and you seem to be the only person working on improving these drivers. I'm curious how your changes have been working for you. I'd be happy to test them if you would provide build instructions.

What did the "Fix Bluetooth" commit fix? I have had an error at one point where I was unable to remove the pairing. Eventually Windows crashed. I then paired and unpaired with a diff Windows installation, came back to my main install, and Windows auto asked to re-pair and the trackpad worked again.

Do you have any plans to implement the missing battery indicator inside the Settings panel?

### CODE REVIEW

**Comment by 1Revenger1** [comment]
All of these updates so far is to use the finger data better from the trackpad.
This doesn't fix any errors with pairing, battery, etc. unfortunately.

The trackpad does feel better to use, and I think I fixed an issue where the trackpad would stop working over bluetooth (but I haven't used it much). I don't have anyway to sign this, so I have to have test signing mode enabled when using the trackpad over bluetooth.

**Comment by 1Revenger1** [comment]
Also, I have no clue how to implement the battery indicator, if it is possible. It appears to be checking Bluetooth LE GATT data, which the MT2 does not use. I'm still new with working with windows though.

**Comment by Trevor-Z** [comment]
You don't plan to release this, but how about creating a pr?

**Comment by Trevor-Z** [comment]
I don't know how GitHub works in this regard, is he notified when there's activity in the forks? Otherwise, he might not even know about what you're doing.

**Comment by mmikeww** [comment]
i'm afraid that imbushuo might not even be updating it anymore

**Comment by ericreeves** [comment]
Any chance you could publish some docs on how to build this for folks who have never used Visual Studio to compile a Windows app/driver before?  I'd love to give it a shot.

Thanks either way for your work!

**Comment by ThiagoAnd** [comment]
@1Revenger1 , i believe  imbushuo  dont work anymore on the project. Please, dont let this project dead!

**Comment by jerryngm** [comment]
@ericreeves I have complied it, you can try it here:
[AMD64.zip](https://github.com/1Revenger1/mac-precision-touchpad/files/12407528/AMD64.zip)

**Comment by VoeGalore** [comment]
some instruction for who just wish to make our own driver from source is greatly appreciated 😉

**Comment by weilitao** [comment]
Hi, when install this file, I have this error: "A certificate chain processed, but terminated in a root certificate which is not trusted by the  trust provider."

So would you please give me some instruction how to install this driver? The original one from imbushuo do not have this problem.

> @ericreeves I have complied it, you can try it here: [AMD64.zip](https://github.com/1Revenger1/mac-precision-touchpad/files/12407528/AMD64.zip)

**Comment by averycblack** [comment]
> Hi, when install this file, I have this error: "A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider."
> 
> So would you please give me some instruction how to install this driver? The original one from imbushuo do not have this problem.
> 
> > @ericreeves I have complied it, you can try it here: [AMD64.zip](https://github.com/1Revenger1/mac-precision-touchpad/files/12407528/AMD64.zip)

This is expected. I'm guessing the driver is signed using a test certificate, which you have to go in and install as a trusted root. I wouldn't recommend installing someone else's certificate like this, do so at your own risk. This is the main reason I haven't uploaded anything. I may look into making a PR at some point in Imbusho's repo - I just haven't had the time too recently.

@VoeGalore 
For building yourself - should be fairly simple. I think you need WDK (Windows Driver kit), then you should be able to build the universal package. This should build all of the other projects. I was able to get the user mode drivers to install and run, but the kernel space ones (AmtPtpHidFilter, AmtPtpDeviceUsbKm, and AmtPtpDeviceSpiKm) all require test signing mode enabled in Windows. I again wouldn't really recommend doing this, especially since many game anti-cheats don't like test signing mode enabled.

The two drivers I have modified are AmtPtpHidFilter and AmtPtpDeviceUsbUm, which should modify the Magic Trackpad 2 behavior. Older USB Wellspring touchpads may be a bit broken (I don't have windows on my MacBookPro9,2 to test with). AmtPtpHidFilter is used with the Magic Trackpad 2 over Bluetooth, while the userspace Usb driver should work with the trackpad while connected over USB.

**Comment by averycblack** [comment]
> I may look into making a PR at some point in Imbusho's repo - I just haven't had the time too recently.

Recently took the time to clean up the changes and to create a PR in Imbusho's repo. Includes fixes for tip switch and confidence values, as well as hopefully resolving the touchpad randomly losing functionality without repairing/a restart.

**Comment by mmikeww** [comment]
Thanks for your work. Lets hope imbushuo is still active and merges it

**Pull request closed without merging**
